In [9]:
using LinearAlgebra

In [73]:
threshold = 2

2

In [74]:
spiketrain = hcat(zeros(Float32, 5, 4), rand([0., 1.], 5, 100))

5×104 Matrix{Float64}:
 0.0  0.0  0.0  0.0  0.0  0.0  0.0  1.0  …  0.0  0.0  1.0  0.0  0.0  0.0  0.0
 0.0  0.0  0.0  0.0  1.0  0.0  0.0  1.0     0.0  0.0  0.0  0.0  1.0  1.0  0.0
 0.0  0.0  0.0  0.0  1.0  1.0  0.0  1.0     0.0  1.0  1.0  1.0  0.0  0.0  1.0
 0.0  0.0  0.0  0.0  1.0  1.0  1.0  0.0     0.0  1.0  0.0  1.0  0.0  1.0  0.0
 0.0  0.0  0.0  0.0  1.0  1.0  1.0  0.0     1.0  0.0  0.0  1.0  0.0  0.0  1.0

In [75]:
function mask(potential)
    spike_out = zeros(size(potential))
    kernel = [.0625 .125 .25 .5 1.]
    t = 5
    while t <= size(potential)[2]
        v = dot(potential[t-4:t], kernel)
        if v > threshold
            spike_out[t] = 1.
            potential[t-3:t+1] = [0 0 0 0 0 ]
            t += 1
        end
        t += 1
    end
    return spike_out
end

mask (generic function with 1 method)

In [76]:
w = rand(5, 5) * 0.2

5×5 Matrix{Float64}:
 0.064481   0.0139096  0.196931    0.142397   0.00328801
 0.0691523  0.116002   0.102366    0.0466954  0.0633898
 0.192122   0.127635   0.120177    0.157985   0.19771
 0.147406   0.170874   0.00473909  0.0995363  0.0822955
 0.0688047  0.0087239  0.194934    0.0853888  0.0489231

In [77]:
vsoma = sum(w * spiketrain, dims=1)

1×104 Matrix{Float64}:
 0.0  0.0  0.0  0.0  1.9839  1.54675  …  0.437144  0.969146  1.01475

In [78]:
spike_out = mask(vsoma)

1×104 Matrix{Float64}:
 0.0  0.0  0.0  0.0  0.0  1.0  0.0  0.0  …  0.0  0.0  0.0  1.0  0.0  0.0  0.0

In [79]:
sum(spike_out)

28.0

In [83]:
function loss(st_hat, st)

10-element Vector{Float64}:
 0.0
 0.0
 1.0
 0.0
 0.0
 0.0
 1.0
 0.0
 0.0
 0.0